### PR TITLE
Sales processor refactor

### PR DESCRIPTION
**Pull request by GalacticWafer**
This is a huge refactoring of the <code>SalesProcessor</code> to unify the logic for dealing with transactions.

- Product.java:
    - <code>TransactionItem</code> renamed to <code>Product</code> 
    - Most of the things that we know from <code>SalesProcessor</code> class (formerly named <code>TransactionItem</code>) are now in Order.java
    - Very light weight object; we can refactor to get rid of all fields except <code>productId </code> and <code>requestedQuantity</code>.

- Order.java:
    - Created as a wrapper class for an <code>ArrayList </code>of <code>Product </code>objects, and related operations. 
    - Most of the fields we were storing in <code>Product </code> (formerly named <code>TransactionItem</code>)  objects  has been moved to Order.java, such as <code>orderId</code>, <code>location</code>, <code>dateAccepted</code>, <code>dateOrdered </code>
		<code>isSale</code>, <code>canProcess</code>, and <code>status </code>. All <code>Product </code>objects of the same order share these qualities.  
    - Most of the operations are done to an entire order by iterating over the <code>ArrayList</code>of products.

- SalesProcessor.java:
    - Can process a csv file or email inbox
    - Still needs more advanced testing. Only rudimentary tests have been done to make sure quantities are changing as expected.
    - <code>SalesProcessor </code> now must be instantiated, which avoids null pointers, as well as static call issuses.
    - In order to update all the quantities and add entries to the sales table in SQL, <code>SalesProcessor </code> must now be closed out using <code>SalesProcessor </code> method.

- Restoration.java
    - <code>SalesProcessor </code> objects must be instantiated, which avoids null pointers, as well as static call issuses.

- Crud.java
    - Removed redundant/excessive methods:
        - <code>deleteAllRecords </code>
        - <code>quoteWrap </code>
        - <code>deleteTable </code>
        - <code>find </code>
        - <code>getType </code>
        - <code>prepareStatement </code>
        - <code>setAutoCommit </code>
        - <code>use </code>

    - Refactored instantiation to call <code>USE </code> sql statament to set the working database to your database. Also concatenated the database name to the beginning of <code>tableName</code> in all query calls using a table  name for reliability. 
    
Other Notes: 
- Everyone now has their own database to experiment in, so contact me if there are any problems getting your UNTRACKED Credentials.java or Main.java classes to work correctly.

### CODE REVIEW

**Review by OutbreakSource — APPROVED** [review]
Excited to see a lot of code be removed. Hoping for faster times when it comes to emailing and processing orders. Let's just make sure everything functions after this giant refactor, stabilization is key here for the final sprint, which is coming pretty soon

**Review by ubello64 — APPROVED** [review]
I especially like the refactoring in Crud, it is great to see Crud decrease in size but still be as effective. At first I was confused as to why so much was deleted but then through careful reading of the major classes I understand why. Hopefully we can then use these new commits and perform more testing in another branch.

**Review by dbowling21 — APPROVED** [review]
Miles of improvement towards a more stable working codebase. Especially for analytics. Separating the database for each person was a great idea. Like Daniel said, making sure this is in fact stable is key. Lots of testing going forward will hopefully confirm this. Nice work!

**Comment by Adam-Prieto** [comment]
Looked into files, need to test everything?

**Review by Adam-Prieto — APPROVED** [review]
Code is extremely detailed, and probably needs to be tested. If so, getting started sooner rather than later is ideal.

**Pull request merged**
