### PR TITLE
Chart Implementation

### PR DESCRIPTION
**Pull request by dbowling21**
New classes to define chart types and chart creation. GUI now has a textfield for date that when filled displays buttons for various chart analytics.

### CODE REVIEW

**Review by OutbreakSource — APPROVED** [review]
Glad to have some charts being made, final steps are to make sure everything works and outputs properly so we can use my Emailer to send them their way to our 'financial team'

**Comment by GalacticWafer** [comment]
The enum for Tables is a great idea. This allows a much more modular and compact use of creating charts. While I do think it may be beneficial to look at a fully-fledged factory design pattern in the future, this is good for now.

**Review by GalacticWafer — APPROVED** [review]
This kind of compact creation of swing elements using enums is something we should also think about doing for the rest of the gui

**Review by Hamadesigns — APPROVED** [review]
Search field for date can still accept any characters. should limit to just numbers

**Pull request merged**
