### PR TITLE
-Fixed reading/writing emails from other services (yahoo,google itself)

### PR DESCRIPTION
**Pull request by OutbreakSource**
-Email recipient was blank when reading emails from other services (Outlook was working)
-Changed Date parameter to LocalDate to work when parsing the dates
-Created ForeverChecker.java for future automation

### CODE REVIEW

**Comment by GalacticWafer** [comment]
Good work, we still need to figure out why we were able to send emails in the first place. I think we will probably see some other bugs soon unless we can hunt that down. Still need to find out why these events are not ending up in the sales table.

**Review by GalacticWafer — APPROVED** [review]
Just keep in mind that we are only using this for demo day as a stable version. TransactionItem.java, SalesProcessor.java, and Emailer.java are all being refactored for improved readability, reliability, and performance.

**Comment by Adam-Prieto** [comment]
Pull Request 10/26. Only for stability reasoning as refactoring is being done.

**Review by Adam-Prieto — APPROVED** [review]
Pull Request 10/26. Only for stability reasoning as refactoring is being done.

**Pull request merged**
