### PR TITLE
Now reqires manual entry of usernames and passwords for every run.

### PR DESCRIPTION
**Pull request by GalacticWafer**
Now you must create an instance of Credentials, as demonstrated in Main.java.
Now uses a package customerrelationsmanagement for the entire program.

### CODE REVIEW

**Review by Hamadesigns — APPROVED** [review]
reviewed changes(particularly credentials class)

**Review by OutbreakSource — APPROVED** [review]
Hopefully, we don't have any more breaches. Everyone reading this, make sure to not EXPOSE anything related to the new setup of the server. One month left!

**Comment by Adam-Prieto** [comment]
Reviewed 11/7

**Review by dbowling21 — APPROVED** [review]
Good job getting things running again Malcolm, a lesson to us all for sure. We need to double-check there are no remaining branches that still have tracked credentials or main classes.

**Pull request merged**
