### PR TITLE
Asset Graphing

### PR DESCRIPTION
**Pull request by dbowling21**
Updated Gui to be able to run the getAssetTotal total method and display graphically day by day to the charts directory. Adding the ability to clear this directory in restoration later would be a good idea.

### CODE REVIEW

**Comment by GalacticWafer** [comment]
Some observations:
- Make the chart directory and git add it so that we don't have to wory about FileNotFoundException.
    - Make sure that if the directory doesn't exist, the we make it before we start.
- Use an enhanced switch statement for chartTitle.

**Comment by GalacticWafer** [comment]
- Since the loop that creates the charts is already iterating through dates, it would make more sense to finish off other daily statistics at the same time.  
- Because the `sales` table holds information about all orders (including cancelled and invalid ones), all analytics queries need to also be checking `where status > 1` (because 2 = processed, and 3 = fulfilled). 
- At this point, it makes more since to create a new `class Analytics`, which handles:     
	- Object creation for `JFreeChart`s     
    - Looping through dates     
	- Only executing a new chart creation and new statistics _**when the date is a new date in the loop**_ (currently, multiple products on the same day will each trigger a new chart, but there should only be one per day).     
	- Calculating who the top ten customers are and what the top ten products are. Both of these are by revenue, year-to-date.  If possible, also include month-to-date calculations for this point.
    - Some of the fields and features this class should have:        
        - `LinePlot` object        
        - `Crud` object        
        - `File` object holding a directory to `Analytics/`        
        - Create a new file for each date. For example `Analytics/2020-11-06` for today.        
        - Save the chart as a .png file, and a the statistics as a .txt file in that day's folder        
        - Make sure that your logic can be run for all of this with a single method call, and the date as a parameter. This will allow for continuous updates, and future-proof this class in the coming weeks.

**Review by ubello64 — APPROVED** [review]
I like the addition of an analytics class, reduces complexity. The refactoring in CRUD is also very helpful.

**Comment by dbowling21** [comment]
Still, a few TODO's I need to touch on tonight with one last commit but otherwise should be ready to be merged afterward

**Review by OutbreakSource — APPROVED** [review]
Excited to finally start using the Emailer created a month ago with the code/image you guys implemented. Good job to everyone who worked on this. Automation will be our next step into the final product

**Comment by Adam-Prieto** [comment]
Reviewed 11/7

**Comment by dbowling21** [comment]
I will address the time complexity of generateTimePlot next sprint

**Pull request merged**
